[package]
name = "atom_core"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.25"
arrow = "53.0"
ort = { version = "2.0.0-rc.9", features = ["download-binaries", "ndarray", "coreml"] }
ndarray = "0.16"
anyhow = "1.0"
rayon = "1.8"
